### ISSUE TITLE
Plank sack number of planks overlay

### ISSUE THREAD

**Issue by BainoBigBalls** [TheStonedTurtle/Mahogany-Homes#3]
Knowing the amount of planks that remain within your sack using an overlay that is similar to what the runepouch overlay does would be fantastic and really round off this great plugin.

https://i.imgur.com/OibEJWL.png

**Comment by TheStonedTurtle** [comment]
As far as I'm aware this functions similarly to the looting bag where the user/client doesn't know the contents in the bag unless checked/prompted by the server. Tracking plank usage manually from animations or repair spots would be the only way to accomplish this, and I'm not sure how reliable that method would be (I don't really do this activity since I'm 99 con already).

Because of this I doubt this feature will ever be added, sorry.

**Comment by evdm97** [comment]
I see this is marked as wontfix. Does this mean you won't accept pull requests of this issue either or just that it's not something you're interested in making yourself? Because i'm interested in looking into it myself.

**Comment by SeaifanAladdin** [comment]
Fyi, this is something that already exists as the Plank Sack plugin maintained by [Enriath/external-plugins](https://github.com/Enriath/external-plugins/tree/plank-sack)

**Comment by TheStonedTurtle** [comment]
> Fyi, this is something that already exists as the Plank Sack plugin maintained by [Enriath/external-plugins]
(https://github.com/Enriath/external-plugins/tree/plank-sack)

Closing as this plugin exists and I'm not going to reinvent what Enriath has already done.
