### ISSUE TITLE
Suggestion for M'Homes UI/info. display

### ISSUE THREAD

**Issue by sippingchai** [TheStonedTurtle/Mahogany-Homes#5]
Say, for example, I get a contract for Mariah. At 92 con. I don't need to know her location or to click the map, etc. Rather, I just need to see 'Mariah' in case I forget what my contract is (can quickly glance). Doing M'Homes on a UIM, one can easily forget their contract if they are at teaks afking back their plank stock (or if log out for other accs ofc). As it stands the info. takes a bit too much space on my screen and would be nice if it were just an option to display the name only.

**Comment by Box-Of-Hats** [comment]
@sippingchai  Looks like you can toggle these now

![image](https://user-images.githubusercontent.com/9083502/134252867-2e3dbb54-57aa-4721-97f0-7dd7173759c5.png)

**Comment by TheStonedTurtle** [comment]
I've fixed the `World Map Icon` toggle so that when its disabled the overlay text is removed as well, so now the overlay is smaller. I've kept the hint there as I believe the hint doesn't add enough room that it's worth having a separate config option just for controlling whether its displayed. This was changed in commit 7f9a98a1ef6dc1252d0cbd594a9d558ab4bac879

![image](https://user-images.githubusercontent.com/29030969/139602661-e9e87b24-94ea-4527-a1bd-aee480c12d23.png)
